# Generated by Django 6.0.5 on 2026-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
