# Generated by Django 6.0.5 on 2026-05-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_datatreinamento_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_treinamento',
            field=models.ManyToManyField(blank=True, null=True, to='consultas.datatreinamento'),
        ),
    ]
