# Generated by Django 6.0.5 on 2026-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_pergunta_data_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_treinamento',
            field=models.ManyToManyField(blank=True, to='consultas.datatreinamento'),
        ),
    ]
